name = "envars"
version = "1.0.0"

[deployment]
permission = "private"
nodes = 4

[build]
dir = "build"
entry = "envars_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "envars.wasm"
command = "npm run build:release"
